### PR TITLE
Simplified API prototype

### PR DESCRIPTION
**Pull request by phile314**
(Turns out you can't reopen a pull-request after a force-push..... original was #11 )

Updated version of my original pull request. Keeps the existing Tasty API, but changes internals and adds a new API. I did split it into 3 commits, it's probably easiest to look at each of them seperately.

As a short description of the interactive mode, it executes all golden tests. If golden == actual, nothing interesting
happens. If golden is missing (e.g. new test), it show the actual value and asks whether to accept that.
Similar for golden /= actual, it shows the diff and asks whether to accept/reject the new value. Interactive mode only works/tested on linux right now, but could be easily extended to other OS.

### CODE REVIEW

**Comment by phile314** [comment]
Did you have any chance to look at this yet?

**Comment by feuerbach** [comment]
Not yet, sorry :( It is on my todo list.

**Comment by phile314** [comment]
Thanks for the review. I fixed most of the the things you mentioned, for two items I did put my questions next to your comments.

**Comment by phile314** [comment]
Everything should be fixed as discussed now. If there is anything else I should change, let me know.

**Comment by feuerbach** [comment]
I just started reviewing the actual interactive update code, and there are many more things I'm not happy about, but I really don't have time to dig into this. Also, I imagine you're probably tired of this drag, too.

So may I request that you release this as a new package of your own? I'm sure the code is useful, I just don't feel comfortable about having to maintain it.

**Comment by phile314** [comment]
Sure, no problem. Anyway, thanks for taking the time to discuss this.

**Comment by feuerbach** [comment]
@phile314 Take a look at #13. It's probably present in your fork.

I suspect that the way I fixed it won't apply to your fork, however.

**Comment by phile314** [comment]
Thanks for the message. I ported all changes to my fork, and it looks fixed.

I also tried coming up with a test case. Running another tasty consoleTestReporter inside a testcase makes the console output a bit ugly, but it works.... Nothing special, maybe you find it helpful anyway:
https://github.com/phile314/tasty-silver/blob/master/tests/test.hs#L44-L60

**Pull request closed without merging**
