### PR TITLE
Resurrect old GHC support

### PR DESCRIPTION
**Pull request by phadej**
I made revision to `2.3.2.1` https://hackage.haskell.org/package/tasty-golden-2.3.2.1/revisions/

The old GHC support is import for `Cabal`, which tries to support old GHCs (for custom setups, 5 year window at least).

Thus I added CI jobs for older GHCs as well

### CODE REVIEW

**Comment by feuerbach** [comment]
I'm happy to bump the support window for old ghcs in tasty/tasty-golden from 3 years to 5 years. I'm not however happy with an indefinite support policy. That's just not sustainable when new ghcs appear all the time and the old ones never retire.

I'll try to attend to this later today.

**Comment by phadej** [comment]
As you can see, you also broke `aeson` test-suite, so if you decide to drop support for older GHCs, please keep at least lower bounds up to date (i.e. what you test, don't speculate).

**Comment by feuerbach** [comment]
> keep at least lower bounds up to date (i.e. to what you actually test, don't speculate)

Not sure how this would work in practice. Do you have an example package that does that?

**Comment by phadej** [comment]
Essentially all my packages do that. I lookup from `ghc-pkg list` or https://gitlab.haskell.org/ghc/ghc/wikis/commentary/libraries/version-history which library versions are bundled with GHC and set those a lower bounds.
With other packages I keep bounds quite high, as far as there are install plans.

For example in `tree-diff` I do split `build-depends` into two parts, GHC boot libs, and others:
https://github.com/phadej/tree-diff/blob/master/tree-diff.cabal#L83-L106 I essentially never touch the first group (except if I change the GHC support windows), with later part I occasionally simply drop support for older library versions.

E.g. at this point allowing old `ansi-terminal` versions shouldn't be necessary, I might take a look what versions are in few recent Stackage snapshots to judge how much ecosystem is caught up.

The reason to drop them is because they aren't actively tested, nor used, as upgrading non-boot libraries is much less hassle then boot libraries.

Note that CI (`haskell-ci`) does by default test with boot libraries pinned (i.e. there are constraint of form `transformers installed`), so one can be sure that lower bounds for boot libraries are exercised, with other libraries the test matrix would increase.

Yet, e.g. `servant-blaze` is explicitly tested against multiple major `servant` versions https://github.com/haskell-servant/servant-blaze/blob/master/cabal.haskell-ci
I think I'll drop few older `servant` majors from that matrix, as hopefully most people have upgraded from `servant-0.11` (at least if they consider upgrading `servant-blaze` too). Yet, there haven't been any changes to do in `servant-blaze` so they are still there. (This is something which you could consider doing for e.g. `tasty-golden`, to test against all major versions of `tasty` `tasty-golden` advertises to work with, i.e. `1.0`, `1.1` and `1.2`; with an alternative to bump that lower bound as well).

Lastly, [`cabal-plan`](https://hackage.haskell.org/package/cabal-plan) lists what packages are picked for the install plan (and `haskell-ci` tries list used dependencies too, look for `cat cabal.project.freeze | ...` entry), so you can see which are the dependencies picked up).

**Comment by feuerbach** [comment]
So looking at https://github.com/phadej/tree-diff/blob/master/tree-diff.cabal#L83-L106, I see that you restrict vector to >= 0.12, yet travis tests with vector ==0.12.1.2 (https://travis-ci.org/phadej/tree-diff/jobs/650553930#L460). Meaning that you could inadvertently use a new function introduced in vector 0.12.1.2 (just like I did with `<$>` here), and your CI wouldn't catch it, right?

**Comment by phadej** [comment]
> Meaning that you could inadvertently use a new function introduced in vector 0.12.1.2 (just like I did with <$> here), and your CI wouldn't catch it, right?

Correct. I do lower bounds checks before releases, especially when there's non-trivial functionality added. For CI it's too expensive. E.g. for `tasty-golden` a tool I use took

```
usr: 13365.330s   sys: 1288.670s   cpu: 649.449%   time: 2256.375s
```

which is plenty of time just to tell that mostly things are working.
- It fails with `containers` older than `0.4.1.0`, there are install plans, but building of dependencies fail (not sure which); yet `ghc-7.4.2` ships with `containers-0.4.2.1`. So it's a bit of theoretical problem (yet, having the `containers >=0.4.2.1` would be explicit and helpful for automatic tools).
- That there are no install plans with `optparse-applicative` older then `0.14.0.0`
- and more

Screenshot from 2020-02-20 23-08-36

In `quickcheck-instances` I do have a constraint set in CI however which uses oldest possible dependencies: https://github.com/phadej/qc-instances/blob/master/cabal.haskell-ci, there I want to be very sure that they work, as I don't want `quickcheck-instances` to restrict any install plans (it's a testing library!).

This is good discussion, maybe there should be a tool to "infer" possible lower bounds constraint sets, (even built in into `haskell-ci`) so you can add them to the CI. The time cost to have "hard coded" set is relatively small, but then lower-bounds won't accidentally bit rot.

**Comment by phadej** [comment]
Rebased (now this only adds Travis jobs, as `<$>` usage was removed in `master`)

**Comment by feuerbach** [comment]
Thanks.

**Pull request closed without merging**
