### PR TITLE
Add golden test for text files

### PR DESCRIPTION
**Pull request by sapek**
After some experimentation it turns out that displaying diff will work only for ASCII files. While we could convert other encodings to `String` via user provided function, `tasty` can't display non-ASCII characters in the test results anyways.

### CODE REVIEW

**Comment by feuerbach** [comment]
> tasty can't display non-ASCII characters in the test results anyways.

Why is that? Please open an issue.

**Comment by sapek** [comment]
feuerbach/tasty#113

**Comment by sapek** [comment]
So since feuerbach/tasty#113 looks like a Windows limitation (or at most Windows specific `putStr` bug) it probably makes sense to go back to the original plan and expose the function that converts `ByteString` to `String`. Thoughts?

**Comment by sapek** [comment]
In the second commit there is an option exposing decoding function to the user. I think this is better than exposing pretty printing function for two reasons:
- breaking of the text into lines is after decoding
- user doesn't need to import `Text.PrettyPrint`

**Comment by sapek** [comment]
Another thing to consider is whether the action should be returning `ByteString` or `ByteString.Lazy`. The argument for lazy is consistency with `goldenVsString`. The argument for strict is consistency of `ByteString`s used within the `goldenVsText` API (in the action and decode function).

**Comment by feuerbach** [comment]
If the new function only works for text, why does action even return a bytestring instead of, well, text?

**Comment by feuerbach** [comment]
I took your patch and made a few amendments; the result is in the `internal-diff` branch.

Now, there are a couple of things left:

* if I remove the line 2 in your golden test file, here's what I get:

    ```
    --- tests/golden
    +++ test output
    @@
     1
    +2
    @@
     3
    ```

    What's the point of the `@@` lines? I think they are supposed to give line
    numbers, but they don't.

* Otherwise, the test you added isn't very useful since it doesn't even
  exercise the new functionality. So either remove it or change it to be more
  useful.

**Comment by sapek** [comment]
So you want `goldenVsText` to support only UTF-8 files? 

As for the function name, did you consider `Diff` suffix to mean *"allows specifying diff algo"* rather than *"displays diff on failure"*? I can't think of a reason why one would want top compare text files and display anything other than diff on failure, so `Diff` name suffix seems redundant.

The way diff is displayed is controlled by the `Data.Algorithm.DiffContext` module so any improvements, like displaying missing line numbers, would go there.

**Comment by feuerbach** [comment]
Sorry, I have to close this. I am just not that interested in this feature to take on maintainership of new code — especially since I would need to deal with the issues in the Diff library.

Feel free to release as a separate package.

**Pull request closed without merging**
